name: 'CMake build'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Windows:
    name: Windows ${{ matrix.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [windows-latest]
        compiler: ["msvc"]
 
    env:
      CMAKE_PRESET : windows-${{ matrix.compiler }}-release

    steps:
      - name: "Matrix contents"
        run: |
          Write-Host "${{ matrix.compiler }}"
          Write-Host "${{ env.CMAKE_PRESET }}"

  Linux:
    name: Linux ${{ matrix.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-latest]
        compiler: ["clang", "gcc"]
        cmake_preset: [windows-${{ matrix.compiler }}-release]
 
    steps:
      - name: "Matrix contents"
        run: |
          echo "${{ matrix.compiler }}"
          echo "${{ matrix.cmake_preset }}"

  macOS:
    name: macOS ${{ matrix.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [macos-latest]
        compiler: ["clang", "gcc"]
        cmake_preset: [windows-${{ matrix.compiler }}-release]
 
    steps:
      - name: "Matrix contents"
        run: |
          echo "${{ matrix.compiler }}"
          echo "${{ matrix.cmake_preset }}"

