--- 
jobs: 
  Linux: 
    name: "${{ matrix.name }}"
    runs-on: "${{ matrix.image }}"
    steps: 
      - 
        name: "Matrix contents"
        run: |
            echo "${{ matrix.name }}"
            echo "${{ matrix.compiler }}"
            echo "${{ matrix.cmake_preset }}"
    strategy: 
      fail-fast: false
      matrix: 
        cmake_preset: "windows-${{ matrix.compiler }}-release"
        compiler: 
          - clang
          - gcc
        image: ubuntu-latest
        name: "Linux ${{ matrix.compiler }}"
  Windows: 
    name: "${{ matrix.name }}"
    runs-on: "${{ matrix.image }}"
    steps: 
      - 
        name: "Matrix contents"
        run: |
            Write-Host "${{ matrix.name }}"
            Write-Host "${{ matrix.compiler }}"
            Write-Host "${{ matrix.cmake_preset }}"
    strategy: 
      fail-fast: false
      matrix: 
        cmake_preset: "windows-${{ matrix.compiler }}-release"
        compiler: 
          - msvc
        image: windows-latest
        name: "Windows ${{ matrix.compiler }}"
  macOS: 
    name: "${{ matrix.name }}"
    runs-on: "${{ matrix.image }}"
    steps: 
      - 
        name: "Matrix contents"
        run: |
            echo "${{ matrix.name }}"
            echo "${{ matrix.compiler }}"
            echo "${{ matrix.cmake_preset }}"
    strategy: 
      fail-fast: false
      matrix: 
        cmake_preset: "windows-${{ matrix.compiler }}-release"
        compiler: 
          - clang
          - gcc
        image: macos-latest
        name: "macOS ${{ matrix.compiler }}"
name: "CMake build"
true: 
  pull_request: 
    branches: 
      - main
  push: 
    branches: 
      - main
  workflow_dispatch: ~
