name: 'CMake build'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Windows:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        name: "Windows ${{ matrix.compiler }}"
        image: windows-latest
        compiler: ["msvc"]
        cmake_preset: windows-${{ matrix.compiler }}-release
 
    steps:
      - name: "Matrix contents"
        run: |
          Write-Host "${{ matrix.name }}"
          Write-Host "${{ matrix.compiler }}"
          Write-Host "${{ matrix.cmake_preset }}"

  Linux:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        name: "Linux ${{ matrix.compiler }}"
        image: ubuntu-latest
        compiler: ["clang", "gcc"]
        cmake_preset: windows-${{ matrix.compiler }}-release
 
    steps:
      - name: "Matrix contents"
        run: |
          echo "${{ matrix.name }}"
          echo "${{ matrix.compiler }}"
          echo "${{ matrix.cmake_preset }}"

  macOS:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        name: "macOS ${{ matrix.compiler }}"
        image: macos-latest
        compiler: ["clang", "gcc"]
        cmake_preset: windows-${{ matrix.compiler }}-release
 
    steps:
      - name: "Matrix contents"
        run: |
          echo "${{ matrix.name }}"
          echo "${{ matrix.compiler }}"
          echo "${{ matrix.cmake_preset }}"

