name: 'CMake build'

on:
  push:
    branches: [  main  ]
  pull_request:
    branches: [  main  ]
  workflow_dispatch:

env:
  GLOBAL_VAR : "Hello"

jobs:
  Windows:
    name: Windows ${{ matrix.config.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:    [ windows-latest ]
        os:       [ windows ]
        config:
        - {
            compiler: "msvc",
            foo:      "xyz"
          }
 
    env:
      CMAKE_PRESET : ci-${{ matrix.os }}-${{ matrix.config.compiler }}

    steps:
      - name: "Matrix contents"
        run: |
          Write-Host "${{ matrix.config.compiler }}"
          Write-Host "${{ env.CMAKE_PRESET }}"

  Linux:
    name: Linux ${{ matrix.config.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:    [ ubuntu-latest ]
        os:       [ linux ]
        config:
        - {
            compiler: "clang",
            foo:      "xyz"
          }
        - {
            compiler: "gcc",
            foo:      "xyz"
          }
 
    env:
      CMAKE_PRESET : ci-${{ matrix.os }}-${{ matrix.config.compiler }}

    steps:
      - name: "Matrix contents"
        run: |
          echo "${{ matrix.config.compiler }}"
          echo "${{ env.CMAKE_PRESET }}"

  macOS:
    name: macOS ${{ matrix.config.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:    [ macos-latest ]
        os:       [ macos ]
        config:
        - {
            compiler: "clang",
            foo:      "xyz"
          }

 
    env:
      CMAKE_PRESET : ci-${{ matrix.os }}-${{ matrix.config.compiler }}

    steps:
      - name: "Matrix contents"
        run: |
          echo "${{ matrix.config.compiler }}"
          echo "${{ env.CMAKE_PRESET }}"

