name: 'CMake build'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GLOBAL_VAR : "Hello"
  CMAKE_PRESET : ci-${{ matrix.os }}-${{ matrix.compiler }}

jobs:
  Windows:
    name: Windows ${{ matrix.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [windows-latest]
        os: 'windows'
        compiler: ["msvc"]
 
    steps:
      - name: "Matrix contents"
        run: |
          Write-Host "${{ matrix.compiler }}"
          Write-Host "${{ env.CMAKE_PRESET }}"

  Linux:
    name: Linux ${{ matrix.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-latest]
        os: 'linux'
        compiler: ["clang", "gcc"]
 
    steps:
      - name: "Matrix contents"
        run: |
          echo "${{ matrix.compiler }}"
          echo "${{ env.CMAKE_PRESET }}"

  macOS:
    name: macOS ${{ matrix.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [macos-latest]
        os: 'macos'
        compiler: ["clang", "gcc"]
 
    steps:
      - name: "Matrix contents"
        run: |
          echo "${{ matrix.compiler }}"
          echo "${{ env.CMAKE_PRESET }}"

